# Generated by Django 4.1.5 on 2023-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatsuser',
            name='is_email_activated',
            field=models.BooleanField(default=False, verbose_name='Прошел активацию?'),
        ),
        migrations.AlterField(
            model_name='flatsuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='selectedflat',
            name='data_created',
            field=models.DateField(verbose_name='Последнее известное пользователю изменение'),
        ),
    ]
